image: maven:3-openjdk-11

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

services:
  - docker:stable-dind

stages:
  - build
  - dockerize

build:
  stage: build
  tags:
    - common
  script:
    - mvn -ntp package

dockerize:
  image: docker:stable
  stage: dockerize
  tags:
    - common
  only:
    - tags
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
