package tech.pm.kafka.property;

public enum ServiceProperty {
  BOOTSTRAP_SERVER,
  TOPIC_NAME,
  PARTITIONS,
  REPLICATION_FACTOR,
  CONFIG_FILE,
  SOURCE_FILE,
  TIMESTAMP,
  PARTITION,
  OFFSET,
  CONSUMER_GROUP,
  NEW_CONSUMER_GROUP,
  OLD_CONNECTOR_NAME,
  NEW_CONNECTOR_NAME,
  CONNECTORS_URL
}
